version: "3.8"

services:

  mongo-db:
    image: mongo
    container_name: mongo-db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=exampleuser
      - MONGO_INITDB_ROOT_PASSWORD=examplepass


  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=exampleuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=examplepass
      - ME_CONFIG_MONGODB_SERVER=mongo-db